### ISSUE TITLE
parsing iso date -> Error

### ISSUE THREAD

**Issue by inu-web** [vkurko/calendar#516]
Using minified JS Version: event-calendar.min.js v4.4.1

When handing over an eventObject to calendar.updateEvent that has an iso date string as "start" and/or "end" property e.g.:

.updateEvent(eventObj) where eventObj is;
{
    "id": 1150,
    "title": "John Doe",
    "start": "2025-06-25 08:00:00",
    "end": "2025-06-25 16:00:00",
    "extendedProps": {},
    "allDay": false,
    "editable": true,
    "startEditable": true,
    "durationEditable": true,
    "display": "auto",
    "styles": "",
    "classNames": "",
    "resourceIds": [
        "810",
        "855"
    ]
}

the following error occurs:
TypeError: e.getUTCFullYear is not a function
    at je (index.iife.js:12:1)
    at $o (index.iife.js:12:1)
    at kt (index.iife.js:12:1)
    at Proxy.U (index.iife.js:12:1)
    at Proxy.m_eventupdate (calendar.js:552:29)

in https://github.com/vkurko/calendar?tab=readme-ov-file#parsing-event-from-a-plain-object the description of parsing plain object says: conversion should be done automatically from ISO Date - this worked well in v3.5.0 (i used before updating)

in inspector on stepping through the code the problem appears in index.iife.js
import {createCalendar, DayGrid, Interaction, List, ResourceTimeGrid, ResourceTimeline, TimeGrid} from './index.es.js';

export function create(target, options) {
    return createCalendar(target, [
        DayGrid,
        Interaction,
        List,
        ResourceTimeGrid,
        ResourceTimeline,
        TimeGrid
    ], options);
}

export {destroyCalendar as destroy} from './index.es.js';

**Comment by vkurko** [comment]
This issue should be fixed in v4.4.2. Please check and thanks for reporting.

**Comment by vkurko** [comment]
I hope I can close this issue.

**Comment by inu-web** [comment]
Yes, thank you - I can confirm the fix!
🙌
