### ISSUE TITLE
JavaScript module not working in v4.3.0

### ISSUE THREAD

**Issue by Spiky-73** [vkurko/calendar#507]
When I copy the example code within my `main.js`, firefox gives the following error when importing `@event-calendar/core`:
```
Uncaught TypeError: (void 0) is not a function
    <anonymous> index.js:1243
index.js:1243:26
```

I tested the import with `v3.12.0` and it was working fine.

#### `index.html`
```html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/svg+xml" href="vite.svg" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Vite App</title>
  </head>
  <body>
    <div id="app"></div>
    <script type="module" src="main.js"></script>
  </body>
</html>
```
 #### `main.js`
```js
import { createCalendar, TimeGrid } from '@event-calendar/core'
import '@event-calendar/core/index.css'

let ec = createCalendar(
  document.getElementById('app'),
  [TimeGrid],
  {
    view: 'timeGridWeek',
    events: [
      {
        start: '2025-05-26',
        end: '2025-05-28',
        title: 'event 1',
        display: 'background',
      },
      {
        start: '2025-05-27',
        end: '2025-05-28',
        title: 'event 2',
      },]
  }
);
```

#### `package.json`
```json
{
  "name": "app-eventcalendar-js",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "devDependencies": {
    "@event-calendar/core": "^4.0",
    "vite": "^6.3.5"
  }
}
```

**Comment by vkurko** [comment]
I confirm the issue with `svelte >= 5.33.0` and will provide a fix soon.

**Comment by vkurko** [comment]
The issue should be fixed in v4.3.1. Please check.

**Comment by Spiky-73** [comment]
This made it work. Thanks!
